### ISSUE TITLE
不继承你们application 要怎么初始化 

### ISSUE THREAD

**Issue by liupeng110** [MobClub/SMSSDK-for-Android#3]
继承了第三方application   跟你们这个冲突 了怎么办

**Comment by Pan-Gao** [comment]
我们的sdk有多重初始化方法，你可以选择使用手动调用代码来初始化：
`MobSDK.init(context, "你的AppKey", "你的AppSecret");`

**Comment by liupeng110** [comment]
看到了 文档里有 只是没注意 仔细看
